services:
  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/database_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: keyoarbcat
    ports:
      - "5432:5432"

volumes:
  db-data: