services:
  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/database_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: keyoarbcat
    ports:
      - "5432:5432"

  backend:
   image: pdp_backend_docker_image:latest
   depends_on:
     - postgres
   ports:
     - "3002:3002"

  frontend:
   image: pdp_frontend_docker_image:latest
   depends_on:
     - backend
   ports:
     - "8082:8082"

volumes:
  db-data:
  