backend:
  replicaCount: 1
  image:
    name: backend
    repository: cheeseman1213/backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3002

frontend:
  replicaCount: 1
  image:
    name: frontend
    repository: cheeseman1213/frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8082

database:
  replicaCount: 1
  image:
    name: postgres
    repository: postgres
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5432
    