backend:
  replicaCount: 1
  image:
    name: pdp_backend_docker_image
    repository: cheeseman1213/pdp_backend_docker_image
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3002

frontend:
  replicaCount: 1
  image:
    name: pdp_frontend_docker_image
    repository: cheeseman1213/pdp_frontend_docker_image
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8082

database:
  replicaCount: 1
  image:
    name: postgres
    repository: postgres
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5432
    