backend:
  replicaCount: 1
  image:
    name: pdp-backend-docker-image
    repository: cheeseman1213/pdp-backend-docker-image
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3002
  ingress:
    enabled: true
    host: pdp-app-backend.local

frontend:
  replicaCount: 1
  image:
    name: pdp-frontend-docker-image
    repository: cheeseman1213/pdp-frontend-docker-image
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: true
    host: pdp-app-frontend.local

database:
  replicaCount: 1
  image:
    name: postgres
    repository: postgres
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5432
    