apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_charts.fullname" . }}-database
  labels:
    app: {{ include "helm_charts.name" . }}
    chart: {{ include "helm_charts.chart" . }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ include "helm_charts.name" . }}