apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm_charts.fullname" . }}-frontend
  labels:
    app: {{ include "helm_charts.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm_charts.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "helm_charts.name" . }}
        component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.frontend.image.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 8082
          env:
            - name: APP_HOST
              value: http://{{ include "helm_charts.fullname" . }}-backend:{{ .Values.backend.service.port }}
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
