apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_charts.fullname" . }}-frontend
  labels:
    app: {{ include "helm_charts.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm_charts.name" . }}
